server: 
  port: 1203
logging:
  file: common-microservice-ip-api-1203.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8888/eureka/


#数据源：
spring:
  datasource: 
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa: 
    show-sql: false
    hibernate: 
        ddl-auto: update 
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
    properties:  
      hibernate:   
        dialect: ${datasource.jdbc.dialect} 
        temp: 
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法未实现
          
#  datasource: 
#    separator: ;;
##    schema: classpath:/datasource/*.sql
#    initialization-mode: ${datasource.initialization-mode} 
#    continueOnError: false
#    hikari: 
#      minimum-idle: ${datasource.jdbc.minIdle}
#      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.167.202.187:3306/crawler_carrier
#    schema-username: root 
#    schema-password: 12qwaszx
#    username: root
#    password: 12qwaszx
#    type: ${datasource.jdbc.type}
#  jpa: 
#    show-sql: true
#    hibernate: 
#        ddl-auto: update 
#        naming: 
#          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
#    properties:  
#      hibernate:   
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        temp: 
#          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法未实现
          
          

