truncate table billinfo_feetype_item_code;

INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (2, NULL, NULL, '', '收费类型', '合计');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (6, NULL, '011001', '基本套餐费', '收费类型', '套餐及固定费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (7, NULL, '011001', '基本套餐费', '收费类型', '套餐包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (8, NULL, '011001', '基本套餐费', '收费类型', '红包卡套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (9, NULL, '011099', '其他费用', '收费类型', '天翼送话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (10, NULL, '011001', '基本套餐费', '收费类型', '乐享套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (11, NULL, '011004', '短信彩信费', '收费类型', '短信通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (12, NULL, '011006', '业务功能费', '收费类型', '移动业务副卡功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (13, NULL, '011099', '其他费用', '收费类型', '红包返还');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (14, NULL, '011002', '国内通话费', '收费类型', '手机国内通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (16, NULL, '011001', '基本套餐费', '收费类型', 'E9套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (17, NULL, '011099', '其他费用', '收费类型', '  综合信息服务费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (18, NULL, '011006', '业务功能费', '收费类型', '  业务功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (19, NULL, '011004', '短信彩信费', '收费类型', '  短信费（点对点）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (20, NULL, '011001', '基本套餐费', '收费类型', '  天翼套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (21, NULL, '011006', '业务功能费', '收费类型', '  天翼月功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (22, NULL, '011005', '互联网流量费', '收费类型', '  手机上网流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (23, NULL, '011001', '基本套餐费', '收费类型', '  月基本费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (24, NULL, '011004', '短信彩信费', '收费类型', '  短信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (25, NULL, '011002', '国内通话费', '收费类型', '  国内通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (31, NULL, '011099', '其他费用', '收费类型', '其它功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (32, NULL, '011099', '其他费用', '收费类型', '优惠费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (34, NULL, '011001', '基本套餐费', '收费类型', '套餐使用费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (36, NULL, '011006', '业务功能费', '收费类型', '天翼阅读');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (39, NULL, '011003', '异地通话费', '收费类型', '省内漫游通话');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (40, NULL, '011002', '国内通话费', '收费类型', '本地通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (41, NULL, '011005', '互联网流量费', '收费类型', '手机上网及无线宽带使用费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (42, NULL, '011004', '短信彩信费', '收费类型', '国内短信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (43, NULL, '011002', '国内通话费', '收费类型', '国内通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (48, NULL, '011005', '互联网流量费', '收费类型', '上网及数据通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (51, NULL, '011002', '国内通话费', '收费类型', '语音通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (56, NULL, '011099', '其他费用', '收费类型', '套餐及叠加包超出费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (57, NULL, '011099', '其他费用', '收费类型', '综合信息服务费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (58, NULL, '011005', '互联网流量费', '收费类型', '上网费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (59, NULL, '011005', '互联网流量费', '收费类型', '手机上网信息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (60, NULL, '011001', '基本套餐费', '收费类型', '套餐月基本费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (61, NULL, '011006', '业务功能费', '收费类型', '天翼导航车小秘');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (62, NULL, '011004', '短信彩信费', '收费类型', '短信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (63, NULL, '011004', '短信彩信费', '收费类型', '短消息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (64, NULL, '011001', '基本套餐费', '收费类型', '飞Young 4G畅聊版套餐升级流量豪卡20元可选包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (65, NULL, '011099', '其他费用', '收费类型', '套餐超出费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (69, NULL, '011001', '基本套餐费', '收费类型', '月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (70, NULL, '011004', '短信彩信费', '收费类型', '短信网关费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (71, NULL, '011005', '互联网流量费', '收费类型', '手机上网费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (72, NULL, '011004', '短信彩信费', '收费类型', '3、代收信息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (73, NULL, '011099', '其他费用', '收费类型', '3、套餐调整费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (74, NULL, '011005', '互联网流量费', '收费类型', '3、互联网使用费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (75, NULL, '011004', '短信彩信费', '收费类型', '4、代收信息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (76, NULL, '011099', '其他费用', '收费类型', '6、调减/优惠');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (77, NULL, '011099', '其他费用', '收费类型', '4、调减/优惠');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (78, NULL, '011002', '国内通话费', '收费类型', '2、国内通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (79, NULL, '011099', '其他费用', '收费类型', '5、套餐调整费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (80, NULL, '011004', '短信彩信费', '收费类型', '2、短信通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (81, NULL, '011099', '其他费用', '收费类型', '5、调减/优惠');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (82, NULL, '011004', '短信彩信费', '收费类型', '3、短信通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (83, NULL, '011001', '基本套餐费', '收费类型', '1、(合约)套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (84, NULL, '011099', '其他费用', '收费类型', '4、套餐调整费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (85, NULL, '011006', '业务功能费', '收费类型', '彩铃功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (86, NULL, '011001', '基本套餐费', '收费类型', '套餐月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (87, NULL, '011001', '基本套餐费', '收费类型', '月基本费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (88, NULL, '011006', '业务功能费', '收费类型', '来电显示费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (90, NULL, '011004', '短信彩信费', '收费类型', '短信服务费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (92, NULL, '011099', '其他费用', '收费类型', '赠费抵扣');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (98, NULL, '011004', '短信彩信费', '收费类型', '短信彩信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (99, NULL, '011002', '国内通话费', '收费类型', '国内语音通信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (101, NULL, '011099', '其他费用', '收费类型', '代收费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (103, NULL, '011002', '国内通话费', '收费类型', ' 通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (104, NULL, '011004', '短信彩信费', '收费类型', '信息类彩信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (105, NULL, '011099', '其他费用', '收费类型', '零头调整');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (106, NULL, '011006', '业务功能费', '收费类型', ' 龙江沃卡增值业务包(新)');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (107, NULL, '011001', '基本套餐费', '收费类型', '基本套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (108, NULL, '011002', '国内通话费', '收费类型', ' 市话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (109, NULL, '011003', '异地通话费', '收费类型', '国内漫游费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (111, NULL, '011099', '其他费用', '收费类型', '减免');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (112, NULL, '011001', '基本套餐费', '收费类型', '月租');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (113, NULL, '011001', '基本套餐费', '收费类型', ' 基本月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (114, NULL, '011006', '业务功能费', '收费类型', '后向流量月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (115, NULL, '011005', '互联网流量费', '收费类型', '  手机上网流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (116, NULL, '011099', '其他费用', '收费类型', '联通在信信息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (117, NULL, '011006', '业务功能费', '收费类型', '增值业务月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (119, NULL, '011001', '基本套餐费', '收费类型', '套餐月功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (120, NULL, '011099', '其他费用', '收费类型', ' 补收');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (121, NULL, '011099', '其他费用', '收费类型', '-联通在信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (123, NULL, '011002', '国内通话费', '收费类型', ' 网内话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (124, NULL, '011001', '基本套餐费', '收费类型', 'GPRSWAP月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (125, NULL, '011099', '其他费用', '收费类型', '联通在信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (126, NULL, '011005', '互联网流量费', '收费类型', 'GPRSWAP流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (127, NULL, '011006', '业务功能费', '收费类型', '3G包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (128, NULL, '011002', '国内通话费', '收费类型', ' ivpn024国内通话(跨行政区)');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (130, NULL, '011099', '其他费用', '收费类型', '其他营业费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (131, NULL, '011006', '业务功能费', '收费类型', '手机邮箱');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (132, NULL, '011006', '业务功能费', '收费类型', ' 叠加套餐包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (133, NULL, '011001', '基本套餐费', '收费类型', ' 移动业务月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (134, NULL, '011003', '异地通话费', '收费类型', '  国内通话费-异地');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (135, NULL, '011099', '其他费用', '收费类型', '最低消费补收（低消送流量）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (137, NULL, '011006', '业务功能费', '收费类型', '手机音乐包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (138, NULL, '011099', '其他费用', '收费类型', '赠款消费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (139, NULL, '011006', '业务功能费', '收费类型', '  叠加套餐包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (141, NULL, '011006', '业务功能费', '收费类型', '炫铃');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (142, NULL, '011002', '国内通话费', '收费类型', ' 国内通话费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (143, NULL, '011099', '其他费用', '收费类型', ' 代收费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (145, NULL, '011002', '国内通话费', '收费类型', '  国内通话费-本地');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (146, NULL, '011006', '业务功能费', '收费类型', '附加业务月租');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (147, NULL, '011006', '业务功能费', '收费类型', '来电显示');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (148, NULL, '011004', '短信彩信费', '收费类型', '  点对点短信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (149, NULL, '011006', '业务功能费', '收费类型', '其他增值业务使用费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (150, NULL, '011005', '互联网流量费', '收费类型', '-手机上网流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (152, NULL, '011001', '基本套餐费', '收费类型', ' 套餐租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (153, NULL, '011099', '其他费用', '收费类型', '其它增值业务使用费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (155, NULL, '011006', '业务功能费', '收费类型', '流量子业务租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (156, NULL, '011006', '业务功能费', '收费类型', '手机邮箱包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (157, NULL, '011099', '其他费用', '收费类型', ' 优惠/退补');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (158, NULL, '011006', '业务功能费', '收费类型', '4G包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (159, NULL, '011001', '基本套餐费', '收费类型', ' 基本套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (161, NULL, '011004', '短信彩信费', '收费类型', '点对点彩信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (162, NULL, '011005', '互联网流量费', '收费类型', ' 手机上网流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (163, NULL, '011003', '异地通话费', '收费类型', '国内长途费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (164, NULL, '011099', '其他费用', '收费类型', ' Kjava业务');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (165, NULL, '011004', '短信彩信费', '收费类型', ' 点对点彩信');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (166, NULL, '011006', '业务功能费', '收费类型', '基础附加业务功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (167, NULL, '011001', '基本套餐费', '收费类型', '-基本套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (168, NULL, '011006', '业务功能费', '收费类型', '子业务月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (169, NULL, '011001', '基本套餐费', '收费类型', '基本套餐');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (170, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃音乐特惠会员1元');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (171, NULL, '011006', '业务功能费', '收费类型', '增值业务-喜马拉雅FM');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (172, NULL, '011099', '其他费用', '收费类型', 'GSM炫铃特服费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (173, NULL, '011006', '业务功能费', '收费类型', '流量包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (174, NULL, '011004', '短信彩信费', '收费类型', 'GSM短信包月');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (175, NULL, '011006', '业务功能费', '收费类型', '增值业务-绿色邮箱');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (176, NULL, '011006', '业务功能费', '收费类型', '增值业务-腾讯联通版');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (179, NULL, NULL, NULL, '收费类型', '套内语音费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (180, NULL, '011001', '基本套餐费', '收费类型', '自由组合套餐流量月套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (182, NULL, '011001', '基本套餐费', '收费类型', '自由组合套餐语音月套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (183, NULL, '011006', '业务功能费', '收费类型', '增值业务-2元炫铃');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (185, NULL, '011006', '业务功能费', '收费类型', '增值业务-单本阅读B（T）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (186, NULL, '011006', '业务功能费', '收费类型', '增值业务-炫铃DIY（首月免费）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (187, NULL, '011006', '业务功能费', '收费类型', '联通新时讯通信有限公司（手机邮箱6元版）90213');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (188, NULL, '011006', '业务功能费', '收费类型', '新闻早晚报（手机报10655111）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (189, NULL, '011006', '业务功能费', '收费类型', '增值业务-酷阅原创精选包（首月免月租）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (190, NULL, '011006', '业务功能费', '收费类型', '增值业务-漏话信使');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (191, NULL, '011006', '业务功能费', '收费类型', '增值业务-来电秘书 （3元包月）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (192, NULL, '011006', '业务功能费', '收费类型', '增值业务-3元单次订购(元)');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (193, NULL, '011004', '短信彩信费', '收费类型', '信息费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (194, NULL, '011006', '业务功能费', '收费类型', '附加功能-来电显示服务功能费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (195, NULL, NULL, NULL, '收费类型', '套内流量费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (197, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃商店25元按次-2');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (198, NULL, '011006', '业务功能费', '收费类型', '增值业务-来电提醒（当月免费，次月收费）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (199, NULL, '011006', '业务功能费', '收费类型', '增值业务-自动秘书');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (200, NULL, '011006', '业务功能费', '收费类型', '增值业务-内蒙古联通秘书');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (201, NULL, '011001', '基本套餐费', '收费类型', '4G本地套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (202, NULL, '011006', '业务功能费', '收费类型', '增值业务-联通秘书');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (203, NULL, '011006', '业务功能费', '收费类型', '增值业务-网易云音乐');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (204, NULL, '011006', '业务功能费', '收费类型', '随意打语音包月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (205, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃商店4元按次-2');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (206, NULL, '011006', '业务功能费', '收费类型', '增值业务-交通助手（机动车业务1）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (207, NULL, '011003', '异地通话费', '收费类型', 'GSM国内异地移动费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (208, NULL, '011006', '业务功能费', '收费类型', '流量叠加包月套餐费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (209, NULL, '011006', '业务功能费', '收费类型', '增值业务-来电提醒');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (210, NULL, '011006', '业务功能费', '收费类型', '增值业务-小秘书');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (211, NULL, '011006', '业务功能费', '收费类型', '增值业务-来电管家_2元/月(回电宝_2元/月）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (212, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃游戏流量畅玩包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (213, NULL, '011004', '短信彩信费', '收费类型', '彩信费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (214, NULL, '011099', '其他费用', '收费类型', '承诺话费补足费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (215, NULL, '011006', '业务功能费', '收费类型', '增值业务-商务炫铃');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (216, NULL, '011006', '业务功能费', '收费类型', '增值业务-QQ音乐');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (217, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃音乐会员（酷音版-首月免）');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (218, NULL, '011099', '其他费用', '收费类型', '中国联通音乐公司(90115)');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (219, NULL, '011006', '业务功能费', '收费类型', '叠加套餐包');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (220, NULL, '011099', '其他费用', '收费类型', 'GSM赠送分钟包月费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (221, NULL, '011006', '业务功能费', '收费类型', '其他定向流量包月租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (222, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃音乐高级会员（首月免）-1');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (223, NULL, '011004', '短信彩信费', '收费类型', 'GSM特服短信通信费(95555)');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (224, NULL, '011006', '业务功能费', '收费类型', '增值业务-酷车时尚频道包月');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (225, NULL, '011006', '业务功能费', '收费类型', '增值业务-WO+视频优酷定向流量包月');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (226, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃商店3元按次-2');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (228, NULL, '011006', '业务功能费', '收费类型', '增值业务-5元联通秘书');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (229, NULL, '011006', '业务功能费', '收费类型', '增值业务-联通秘书（漏话提醒）2元版');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (230, NULL, '011099', '其他费用', '收费类型', '补收');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (232, NULL, '011006', '业务功能费', '收费类型', '增值业务-沃商店9元按次-2');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (233, NULL, '011006', '业务功能费', '收费类型', '流量半年包租费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (245, NULL, NULL, NULL, '收费类型', '套内来显费用');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (291, NULL, '011005', '互联网流量费', '收费类型', '手机上网流量费');
INSERT INTO billinfo_feetype_item_code (id,createtime,item_code,item_name,item_type,source_name) VALUES (298, NULL, '011002', '国内通话费', '收费类型', '语音通话费');
